feature_medical_term_mapping:
  baseline value: "Baseline Fetal Heart Rate (FHR)"
  accelerations: "Number of accelerations per second"
  fetal_movement: "Number of fetal movements per second"
  uterine_contractions: "Number of uterine contractions per second"
  prolongued_decelerations: "Number of prolonged decelerations per second"
  abnormal_short_term_variability: "Percentage of time with abnormal short term variability"
  percentage_of_time_with_abnormal_long_term_variability: "Percentage of time with abnormal long term variability"
  histogram_max: "Histogram maximum value"
  histogram_number_of_peaks: "Number of peaks in the exam histogram"
  histogram_mode: "Histogram mode"
  histogram_variance: "Histogram variance"
